clients/urls.py
from django.urls import path

from clients.views import *

urlpatterns = [
    path("", homeView, name="home"),
    path("clients/", clientsView, name="getClients"),
    path("professions/", professionsView, name="getProfessions"),
    path("users/", UsersFormView.as_view(), name="getUsers"),

    path("users/list/<int:clinic_id>/<int:profession_id>/", usersView, name="usersList"),
    path("users/list/<int:clinic_id>/<int:profession_id>/<role>/", usersView, name="usersList"),

    path("schedule/", ScheduleFormView.as_view(), name="getSchedule"),
    path("schedule/list/<int:clinic_id>/<int:user_id>/<slug:time_start>/<slug:time_end>/<int:step>/",
         scheduleView, name="scheduleList"),
]

renovatioClinica/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("clients.urls"))
]

clients/models.py
from django.db import models

# Create your models here.

clients/forms.py
import datetime

from django import forms
from django.forms import Select
from django.forms.utils import ErrorList

from clients.dataRequests import getClinics, getProfessions


class UsersForm(forms.Form):
    clinic_id = forms.ChoiceField(label="Клиника")
    profession_id = forms.ChoiceField(label="Специальность")
    role = forms.CharField(label="Должностная роль", required=False)

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False, field_order=None, use_required_attribute=None,
                 renderer=None):
        super().__init__(data, files, auto_id, prefix, initial, error_class, label_suffix, empty_permitted, field_order,
                         use_required_attribute, renderer)

        clinic_id_choices = set()
        for client in getClinics()["data"]:
            clinic_id_choices.add((client["id"], str(client["id"]) + " " + client["title"]))
        self.fields["clinic_id"].choices = sorted(clinic_id_choices)

        professions_id_choices = set()
        for professions in getProfessions()["data"]:
            professions_id_choices.add((professions["id"], professions["name"]))
        self.fields["profession_id"].choices = professions_id_choices


class ScheduleForm(forms.Form):
    clinic_id = forms.ChoiceField(label="Клиника")
    user_id = forms.CharField(label="Сотрудник", widget=Select)
    current_year = datetime.date.today().year
    time_start = forms.DateField(label="Дата начала", widget=forms.DateInput(), input_formats=['%d.%m.%Y'],
                                 initial=datetime.date.today)
    time_end = forms.DateField(label="Дата окончания", widget=forms.DateInput(), input_formats=['%d.%m.%Y'],
                               initial=datetime.date.today)

    STEP_CHOICES = ("10", "15", "20", "30", "60")
    step = forms.IntegerField(label="Шаг в минутах", initial="60",
                              widget=Select(choices=((i, i) for i in STEP_CHOICES)))

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False, field_order=None, use_required_attribute=None,
                 renderer=None):
        super().__init__(data, files, auto_id, prefix, initial, error_class, label_suffix, empty_permitted, field_order,
                         use_required_attribute, renderer)

        clinic_id_choices = set()
        for client in getClinics()["data"]:
            clinic_id_choices.add((client["id"], f"{client['id']}. {client['title']}"))
        self.fields["clinic_id"].choices = sorted(clinic_id_choices)

clients/views.py
import pprint

from django import views
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render
from django.urls import reverse

from clients import dataRequests
from clients.forms import UsersForm, ScheduleForm


def homeView(request):
    return HttpResponseRedirect(reverse(clientsView))


def clientsView(request):
    clients = dataRequests.getClinics()

    if clients["error"]:
        return render(request, "clients/error.html", context={"error": clients["data"]})
    return render(request, "clients/clinics.html", context={"clients": clients["data"]})


def professionsView(request):
    professions = dataRequests.getProfessions()
    if professions["error"]:
        return render(request, "clients/error.html", context={"error": professions["data"]})
    return render(request, "clients/professions.html", context={"professions": professions["data"]})


def usersView(request, clinic_id, profession_id, role=""):
    users = dataRequests.getUsers(clinic_id, profession_id, role)
    if users["error"]:
        return render(request, "clients/error.html", context={"error": users["data"]})

    return render(request, "clients/users-list.html", context={"users": users["data"]})


class UsersFormView(views.generic.FormView):
    form_class = UsersForm
    template_name = "clients/users.html"

    def form_valid(self, form):
        clinic_id = form.cleaned_data["clinic_id"]
        profession_id = form.cleaned_data["profession_id"]
        self.success_url = r"list/{}/{}/".format(clinic_id, profession_id)

        role = form.cleaned_data["role"]
        if role:
            self.success_url += f"{role}/"

        return super().form_valid(form)


class ScheduleFormView(views.generic.FormView):
    form_class = ScheduleForm
    template_name = "clients/schedule.html"

    def form_valid(self, form):
        clinic_id = form.cleaned_data["clinic_id"]
        user_id = form.cleaned_data["user_id"]
        time_start = form.cleaned_data["time_start"]
        time_end = form.cleaned_data["time_end"]
        step = form.cleaned_data["step"]

        self.success_url = "list/{}/{}/{}/{}/{}/".format(clinic_id, user_id, time_start, time_end, step)

        return super().form_valid(form)


def scheduleView(request, clinic_id, user_id, time_start, time_end, step):
    schedule = dataRequests.getSchedule(clinic_id, user_id, time_start, time_end, step)
    if schedule["error"]:
        return render(request, "clients/error.html", context={"error": schedule["data"]})

    return render(request, "clients/schedule-list.html", context={"schedule": schedule["data"]})

templates/403_csrf.html
{% extends 'clients/base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/clients/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>

    <link rel="stylesheet" href="{% static "clients/css/clients.css" %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block styles %}
    {% endblock %}

</head>
<body>

<nav class="navbar">
    <ul class="nav nav-center">
        <li class="nav-item"><a class="nav-link" href="{% url 'getClients' %}">Клиники</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'getProfessions' %}">Специальности</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'getUsers' %}">Сотрудники</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'getSchedule' %}">График Приёма</a></li>
    </ul>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

{% block js %}
{% endblock %}

</body>
</html>

templates/clients/clinics.html
{% extends "clients/base.html" %}

{% block content %}
    <div class="table-responsive">
        <table class="table-hover">
            <caption>Клиники</caption>
            <thead>
            <tr>
                <th>№ клиники</th>
                <th>Название</th>
                <th>ФИО главврача</th>
                <th>№ лицензии</th>
                <th>Дата выдачи лицензии</th>
                <th>Телефон</th>
                <th>Сайт</th>
                <th>Email</th>
                <th>Основной адрес</th>
                <th>Фактический адрес</th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.id }}</td>
                    <td>{{ client.title }}</td>
                    <td>{{ client.doctor_name }}</td>
                    <td>{{ client.license_number }}</td>
                    <td>{{ client.license_date }}</td>
                    <td>{{ client.phone }}</td>
                    <td>{{ client.site }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.address }}</td>
                    <td>{{ client.real_address }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/clients/error.html
{% extends "clients/base.html" %}

{% block content %}
    <h1>Ошибка {{ error.code }}</h1>
    <p>{{ error.desc }}</p>
{% endblock %}

templates/clients/getClients.html
{% extends "clients/base.html" %}

{% block content %}

    <table style="width:100%">
    <caption>Clinics</caption>
        <tr>
            <th>id</th>
            <th>title</th>
            <th>doctor_name</th>
            <th>license_number</th>
            <th>license_date</th>
            <th>phone</th>
            <th>site</th>
            <th>email</th>
            <th>address</th>
            <th>real_address</th>
        </tr>

        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.title }}</td>
                <td>{{ client.doctor_name }}</td>
                <td>{{ client.license_number }}</td>
                <td>{{ client.license_date }}</td>
                <td>{{ client.phone }}</td>
                <td>{{ client.site }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.address }}</td>
                <td>{{ client.real_address }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td>Jill</td>
            <td>Smith</td>
            <td>50</td>
        </tr>

    </table>

{% endblock %}

templates/clients/professions.html
{% extends 'clients/base.html' %}

{% block content %}
    <div class="table-responsive">
        <table class="table-hover">
            <caption>Специальности</caption>
            <thead>
            <tr>
                <th>№</th>
                <th>Название</th>
            </tr>
            </thead>
            <tbody>
            {% for profession in professions %}
                <tr>
                    <td>{{ profession.id }}</td>
                    <td>{{ profession.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/clients/schedule-list.html
{% extends "clients/base.html" %}

{% block content %}

    <table class="table table-hover">
        <caption>График приёма</caption>
        <tr>
            <th>Сотрудник</th>
            <th>Клиника</th>
            <th>Дата начала</th>
            <th>Дата окончания</th>
        </tr>

        {% for user_id, value in schedule.items %}
            {% for item in value %}
                <tr>
                    <td>{{ user_id }}</td>
                    <td>{{ item.clinic_id }}</td>
                    <td>{{ item.time_start }}</td>
                    <td>{{ item.time_end }}</td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>


{% endblock %}

templates/clients/schedule.html
{% extends "clients/base.html" %}
{% load static crispy_forms_tags %}

{% block styles %}
    <link rel="stylesheet" href="{% static "clients/datepicker/datepicker.min.css" %}">
{% endblock %}

{% block content %}

    <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col mb-0">
                {{ form.clinic_id|as_crispy_field }}
            </div>
            <div class="form-group col mb-0">
                {{ form.user_id|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col mb-0">
                {{ form.time_start|as_crispy_field }}
            </div>
            <div class="form-group col mb-0">
                {{ form.time_end|as_crispy_field }}
            </div>
            <div class="form-group col mb-0">
                {{ form.step|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Найти</button>
    </form>
{% endblock %}

{% block js %}
    <script src="{% static "clients/js/clients.js" %}"></script>
    <script src="{% static "clients/datepicker/datepicker.min.js" %}"></script>
    <script>
        $(function () {
            $("#id_time_start").datepicker({
                format: 'dd.mm.yyyy',
                autoHide: true,
            });
            $("#id_time_end").datepicker({
                format: 'dd.mm.yyyy',
                autoHide: true,
            });
        });
    </script>
{% endblock %}

templates/clients/users-list.html
{% extends "clients/base.html" %}

{% block content %}
    <div class="table-responsive">
        <table class="table-hover">
            <caption>Сотрудники</caption>
            <thead>
            <tr>
                <th>№</th>
                <th>Фото</th>
                <th>ФИО</th>
                <th>Дата рождения</th>
                <th>Пол</th>
                <th>№ доверенности</th>
                <th>Дата доверенности</th>
                <th>Телефон</th>
                <th>Email</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.avatar }}</td>
                    <td>{{ user.name }}</td>
                    <td>{{ user.birth_date|date }}</td>
                    <td>{{ user.gender }}</td>
                    <td>{{ user.document_number }}</td>
                    <td>{{ user.document_date }}</td>
                    <td>{{ user.phone }}</td>
                    <td>{{ user.email }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

templates/clients/users.html
{% extends "clients/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col">
                {{ form.clinic_id|as_crispy_field }}
            </div>
            <div class="form-group col">
                {{ form.profession_id|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.role|as_crispy_field }}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Найти</button>
    </form>

{% endblock %}